### ISSUE TITLE
include

### ISSUE THREAD

**Issue by enzoopr** [xRR-debug/cs2_external_internal#13]
![image](https://github.com/insggg/cs2_external_internal/assets/99368496/cc2218d3-cdba-41b8-bcb6-22ccf4ebd19b)
![image](https://github.com/insggg/cs2_external_internal/assets/99368496/13bcefdf-9029-4187-aaa6-cfa206be1003)

i've already included it and it's still giving an error, did I do something wrong?

**Comment by brunoschumacherf** [comment]
Your build is incorrect. Click on the .sln file in the root folder and attempt to build agai

**Comment by enzoopr** [comment]
brasil??

**Comment by brunoschumacherf** [comment]
Ss ksks

**Comment by enzoopr** [comment]
Pode explicar em português, pq n entendi nada kkk

**Comment by brunoschumacherf** [comment]
tem discord?

**Comment by enzoopr** [comment]
tenho, enz_____
